import os
from typing import Dict, Any

class GIPEngine:
    def __init__(self, proposal_dir: str = "docs/proposals"):
        self.proposal_dir = proposal_dir
        os.makedirs(self.proposal_dir, exist_ok=True)

    def generate_proposal(self, title: str, pattern: str, impact: int, compatibility: int, risk: str) -> str:
        filename = f"GIP_{title.lower().replace(' ', '_')}.md"
        filepath = os.path.join(self.proposal_dir, filename)

        content = f"""# Genesis Improvement Proposal (GIP): {title}

**Pattern Name:** {pattern}
**Impact Score:** {impact}/10
**Compatibility Score:** {compatibility}/10
**Risk Assessment:** {risk}

## Summary
Autonomous GIP generated by Genesis Intelligence Harvester v2.

## Recommendation
Integrate this abstract architectural pattern into the Genesis Operating System layer.
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return filepath
